#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs' / 'renderer' / 'generated' / 'pictiq-browser-assets.mjs'


def load_json(rel: str):
    return json.loads((ROOT / rel).read_text(encoding='utf-8'))


def asset(path: Path) -> dict[str, str]:
    return {'path': str(path.relative_to(ROOT)), 'svg': path.read_text(encoding='utf-8')}


def main() -> int:
    lexicon = load_json('lexicon/icon-index.json')
    entities = load_json('entities/entity-index.json')
    numeric = load_json('notation/numeric/index.json')
    icons = {entry['id']: asset(ROOT / 'icons' / 'svg' / f"{entry['id']}.svg") for entry in lexicon['icons']}
    entity_assets = {entry['id']: asset(ROOT / entry['icon_path']) for entry in entities['symbols']}
    numbers = {str(entry['value']): asset(ROOT / entry['svg']) for entry in numeric.get('implemented_numbers', [])}
    data = {
        'generated_from': [
            'lexicon/icon-index.json',
            'entities/entity-index.json',
            'notation/numeric/index.json',
            'icons/svg/*.svg',
            'entities/svg/*.svg',
            'notation/numeric/svg/*.svg',
        ],
        'counts': {'icons': len(icons), 'entities': len(entity_assets), 'numbers': len(numbers)},
        'icons': icons,
        'entities': entity_assets,
        'numbers': numbers,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        '// Generated by tools/generate_browser_renderer_assets.py. Do not edit by hand.\n'
        f'export const PICTIQ_BROWSER_ASSETS = {json.dumps(data, ensure_ascii=False, separators=(",", ":"))};\n',
        encoding='utf-8',
    )
    print(f'OK: wrote {OUT.relative_to(ROOT)} ({len(icons)} icons, {len(entity_assets)} entities, {len(numbers)} numbers)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
