#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs' / 'composer' / 'generated' / 'pictiq-composer-data.mjs'


def load(rel: str):
    return json.loads((ROOT / rel).read_text(encoding='utf-8'))


def main() -> int:
    packs = {p.stem: json.loads(p.read_text(encoding='utf-8')) for p in sorted((ROOT / 'packs').glob('*.json'))}
    profiles = {p.stem: json.loads(p.read_text(encoding='utf-8')) for p in sorted((ROOT / 'profiles').glob('*.json'))}
    data = {
        'generated_from': [
            'lexicon/icon-index.json',
            'lexicon/vocabulary-classification.json',
            'lexicon/compatibility.json',
            'entities/entity-index.json',
            'notation/numeric/index.json',
            'profiles/*.json',
            'packs/*.json',
        ],
        'lexicon': load('lexicon/icon-index.json'),
        'classification': load('lexicon/vocabulary-classification.json'),
        'compatibility': load('lexicon/compatibility.json'),
        'entities': load('entities/entity-index.json'),
        'numeric': load('notation/numeric/index.json'),
        'profiles': profiles,
        'packs': packs,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        '// Generated by tools/generate_composer_data.py. Do not edit by hand.\n'
        f'export const PICTIQ_COMPOSER_DATA = {json.dumps(data, ensure_ascii=False, separators=(",", ":"))};\n',
        encoding='utf-8',
    )
    print(f'OK: wrote {OUT.relative_to(ROOT)} ({len(data["lexicon"].get("icons", []))} icons, {len(data["entities"].get("symbols", []))} entities)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
